pipeline {
    agent any
    environment
    {
     DOCKERHUB_CREDENTIALS = credentials('Dockerhub')
     IMAGE_TAG = '$BUILD_NUMBER'
    }
    stages {
        
        stage('Clone')
        {
            steps{
                cleanWs()
		          git(
                   url:"https://github.com/heloise-viegas/wordsmith-replica.git",
                   branch:"main"
                  )

 
            }
        }



    stage('Push') {
      steps {
        sh 'docker pull heloise1/wordsmithapi'
      }
        post {
          success{
              sh """
                    git clone https://github.com/heloise-viegas/wordsmith-kubernetes-files.git
                    cd ./wordsmith-kubernetes-files/k8s-manifests
	            tag=\$(cat api.yaml | grep "image")
	            echo \$tag
                    var= echo \$tag | awk -F 'wordsmithapi:' '{print \$2}'
	     	    echo \$var
	            echo \$var |sed -i """s/$var/$BUILD_NUMBER/g""" api.yaml
		  
                    
                """
          }  
            
   
  }
    }
  
        
        
        stage('Connect to Minikube from Jenkins') {
            steps {
               withKubeConfig(caCertificate: '', clusterName: 'minikube', contextName: 'minikube', credentialsId: 'Minikube23Aug23', namespace: 'default', restrictKubeConfigAccess: false, serverUrl: 'https://127.0.0.1:32769') 
               {
                   echo "----------------------"
                   sh 'kubectl get all'
               }
            }
			post
			{
			    always{
				echo "Success"
			    }
			}
        }
    }
}
