pipeline {
    agent any
    environment
    {
     DOCKERHUB_CREDENTIALS = credentials('Dockerhub')
     IMAGE_TAG = '$BUILD_NUMBER'
    }
    stages {
        
        stage('Clone')
        {
            steps{
                cleanWs()
            }
        }
        
        stage('Build') {
      steps {
          dir('/home/heloise/.jenkins/workspace/wordsmith/web')
          {
              sh 'pwd'
              sh 'docker build -t heloise1/wordsmithweb:$BUILD_NUMBER .'
          }
      }
    }
    stage('Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        sh 'docker push heloise1/wordsmithweb:$BUILD_NUMBER'
      }
        post {
          success{
      //       sh """#!/bin/bash
      //               git clone https://github.com/heloise-viegas/wordsmith-kubernetes-files.git
		    // """
		  
		 script {

			 // Define the repository URL and local directory
	                def gitRepoURL = 'https://github.com/heloise-viegas/wordsmith-kubernetes-files.git'
	                def localDirectory = './wordsmith-kubernetes-files/k8s-manifests'
	                // Clone the Git repository
	                sh "git clone ${gitRepoURL}"
			 //${localDirectory}
                         def image = sh(script: 'cat ./wordsmith-kubernetes-files/k8s-manifests/web.yaml | grep "image"', returnStdout: true).trim()
			 echo "The value of image is: ${image}"
	                 def delimiter = 'wordsmithweb:'
		         def oldTag = """echo '${image}' | awk -F '${delimiter}' '{print \$2}'"""
			 def processedContent = sh(script: oldTag, returnStdout: true).trim()
		         echo "The value of oldTag is: ${processedContent}"

			 def filePath = './wordsmith-kubernetes-files/k8s-manifests/web.yaml'
			 def fileContent = readFile(filePath).trim()

                    // Replace the old value with the new value
                    def updatedContent = fileContent.replace(processedContent, env.BUILD_NUMBER)
                    // Write the updated content back to the file
                    writeFile(file: filePath, text: updatedContent)
		    // Print the updated content using cat
                    def updatedFileContent = sh(script: "cat ${filePath}", returnStdout: true).trim()
                    echo "Updated file content:"
                    echo updatedFileContent
		   
		    // Stage and commit the changes
                    sh "cd ${localDirectory} && git add web.yaml"
                    sh "cd ${localDirectory} && git commit -m 'Image tag from Jenkins Pipeline'"   
                    // Push the changes to the remote repository
                   // sh "cd ${localDirectory} && git push origin main"
			 withCredentials([gitUsernamePassword(credentialsId: 'hrv-jenkins-pipeline', gitToolName: 'Default')]) {
                    sh "git push -u origin main"
                }
			 // sh "git add web.yaml"
			 // sh "git commit -m 'Updated Image tag from Jenkins Pipeline'"
			 //  withCredentials([gitUsernamePassword(credentialsId: 'hrv-jenkins-pipeline', gitToolName: 'Default')]) {
    //                 sh "git push -u origin main"
    //             }
			 
                }
          }  
            
    always {
      sh 'docker rmi heloise1/wordsmithweb:$BUILD_NUMBER'
      sh 'docker logout'
    }
  }
    }
  
        
        
   //      stage('Connect to Minikube from Jenkins') {
   //          steps {
   //             withKubeConfig(caCertificate: '', clusterName: 'minikube', contextName: 'minikube', credentialsId: 'Minikube23Aug23', namespace: 'default', restrictKubeConfigAccess: false, serverUrl: 'https://127.0.0.1:32769') 
   //             {
   //                 echo "----------------------"
   //                 sh 'kubectl get all'
   //             }
   //          }
			// post
			// {
			//     always{
			// 	echo "Success"
			//     }
			// }
   //      }
    }
}
